// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nhe23/aq-api/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type CitiesSerivce struct {
	mock.Mock
}

// CitiesStartsWith provides a mock function with given fields: searchString
func (_m *CitiesSerivce) CitiesStartsWith(searchString string) ([]*model.City, error) {
	ret := _m.Called(searchString)

	var r0 []*model.City
	if rf, ok := ret.Get(0).(func(string) []*model.City); ok {
		r0 = rf(searchString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.City)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(searchString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCities provides a mock function with given fields: take, after
func (_m *CitiesSerivce) GetCities(take *int, after *string) ([]*model.City, error) {
	ret := _m.Called(take, after)

	var r0 []*model.City
	if rf, ok := ret.Get(0).(func(*int, *string) []*model.City); ok {
		r0 = rf(take, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.City)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*int, *string) error); ok {
		r1 = rf(take, after)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
