// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nhe23/aq-api/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// CountriesSerivce is an autogenerated mock type for the CountriesSerivce type
type CountriesSerivce struct {
	mock.Mock
}

// GetCountries provides a mock function with given fields:
func (_m *CountriesSerivce) GetCountries() ([]*model.Country, error) {
	ret := _m.Called()

	var r0 []*model.Country
	if rf, ok := ret.Get(0).(func() []*model.Country); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Country)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
