// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nhe23/aq-api/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// LocResService is an autogenerated mock type for the LocResService type
type LocResService struct {
	mock.Mock
}

// GetResults provides a mock function with given fields: take, after
func (_m *LocResService) GetResults(take *int, after *string) ([]*model.LocationResult, error) {
	ret := _m.Called(take, after)

	var r0 []*model.LocationResult
	if rf, ok := ret.Get(0).(func(*int, *string) []*model.LocationResult); ok {
		r0 = rf(take, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.LocationResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*int, *string) error); ok {
		r1 = rf(take, after)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
