// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nhe23/aq-api/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// MeasurementsService is an autogenerated mock type for the MeasurementsService type
type MeasurementsService struct {
	mock.Mock
}

// GetResults provides a mock function with given fields: take, after
func (_m *MeasurementsService) GetResults(take *int, after *string) ([]*model.LocationResult, error) {
	ret := _m.Called(take, after)

	var r0 []*model.LocationResult
	if rf, ok := ret.Get(0).(func(*int, *string) []*model.LocationResult); ok {
		r0 = rf(take, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.LocationResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*int, *string) error); ok {
		r1 = rf(take, after)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResultsByCity provides a mock function with given fields: city, take, after
func (_m *MeasurementsService) GetResultsByCity(city string, take *int, after *string) ([]*model.LocationResult, error) {
	ret := _m.Called(city, take, after)

	var r0 []*model.LocationResult
	if rf, ok := ret.Get(0).(func(string, *int, *string) []*model.LocationResult); ok {
		r0 = rf(city, take, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.LocationResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *int, *string) error); ok {
		r1 = rf(city, take, after)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResultsByCountry provides a mock function with given fields: country, take, after
func (_m *MeasurementsService) GetResultsByCountry(country string, take *int, after *string) ([]*model.LocationResult, error) {
	ret := _m.Called(country, take, after)

	var r0 []*model.LocationResult
	if rf, ok := ret.Get(0).(func(string, *int, *string) []*model.LocationResult); ok {
		r0 = rf(country, take, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.LocationResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *int, *string) error); ok {
		r1 = rf(country, take, after)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
