// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type City struct {
	ID        string `json:"_id" bson:"_id"`
	Name      string `json:"name" bson:"name"`
	Country   string `json:"country" bson:"country"`
	Count     int    `json:"count" bson:"count"`
	Locations int    `json:"locations" bson:"locations"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude" bson:"latitude"`
	Longitude float64 `json:"longitude" bson:"longitude"`
}

type Country struct {
	ID        string `json:"_id" bson:"_id"`
	Code      string `json:"code" bson:"code"`
	Name      string `json:"name" bson:"name"`
	Count     int    `json:"count" bson:"count"`
	Cities    int    `json:"cities" bson:"cities"`
	Locations int    `json:"locations" bson:"locations"`
}

type LocationResult struct {
	ID           string         `json:"_id" bson:"_id"`
	Location     string         `json:"location" bson:"location"`
	City         string         `json:"city" bson:"city"`
	Country      string         `json:"country" bson:"country"`
	Measurements []*Measurement `json:"measurements" bson:"measurements"`
	Coordinates  *Coordinates   `json:"coordinates" bson:"coordinates"`
}

type Measurement struct {
	Parameter   string  `json:"parameter" bson:"parameter"`
	Value       int     `json:"value" bson:"value"`
	LastUpdated float64 `json:"lastUpdated" bson:"lastUpdated"`
	Unit        string  `json:"unit" bson:"unit"`
}
