// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type City struct {
	ID        string `json:"_id" bson:"_id"`
	Name      string `json:"name" bson:"name"`
	Country   string `json:"country" bson:"country"`
	Count     int    `json:"count" bson:"count"`
	Locations int    `json:"locations" bson:"locations"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude" bson:"latitude"`
	Longitude float64 `json:"longitude" bson:"longitude"`
}

type Country struct {
	ID        string `json:"_id" bson:"_id"`
	Code      string `json:"code" bson:"code"`
	Name      string `json:"name" bson:"name"`
	Count     int    `json:"count" bson:"count"`
	Cities    int    `json:"cities" bson:"cities"`
	Locations int    `json:"locations" bson:"locations"`
}

type Measurement struct {
	Parameter    string    `json:"parameter" bson:"parameter"`
	Value        int       `json:"value" bson:"value"`
	LastUpdated  time.Time `json:"lastUpdated" bson:"lastUpdated"`
	Unit         string    `json:"unit" bson:"unit"`
	QualityIndex int       `json:"qualityIndex" bson:"qualityIndex"`
}
