// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type City struct {
	ID        string `json:"_id"`
	Name      string `json:"name"`
	Country   string `json:"country"`
	Count     int    `json:"count"`
	Locations int    `json:"locations"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Country struct {
	ID        string `json:"_id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	Count     int    `json:"count"`
	Cities    int    `json:"cities"`
	Locations int    `json:"locations"`
}

type Measurement struct {
	Parameter   string    `json:"parameter"`
	Value       int       `json:"value"`
	LastUpdated time.Time `json:"lastUpdated"`
	Unit        string    `json:"unit"`
}
